# Utiliser l'image officielle d'Apache avec PHP
FROM php:apache

# Copier le fichier index.php dans le dossier de l'application web
COPY index.php /var/www/html/

# Exposer le port 80 (Apache)
EXPOSE 80

