
services:
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetdb
    ports:
      - "3306:3306"
    networks:
      - projet-reseau
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]  
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend_container
    networks:
      - projet-reseau
    depends_on:
       database:
          condition: service_healthy
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=projetdb
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    networks:
      - projet-reseau
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 

  adminer:
    image: adminer
    container_name: adminer_container
    networks:
      - projet-reseau
    ports:
      - "8081:8080"

networks:
  projet-reseau:
    driver: bridge

volumes:
  db_data:


